[database_config]
# url= "sqlite::memory:?cache=shared"  # 开发环境使用 内存型SQLlite
url = "sqlite:./data.db?mode=rwc" # 开发环境使用 文件型SQLlite
max_connections = 10
min_connections = 5

[log_config]
# 日志展示的路径
path = "./log/web.log"
# 高于或者等于 info 的日志就会被记录下来
level = "info"
# 日志文件的大小
size = 10
# 日志输出的位置，文件和控制台
out_kind = ["file", "console"]
# 最多保留 5 个日志文件
roll_count = 5
# 日志时间戳的格式, 表示小时:分钟:秒.微秒
time_format = "%Y-%m-%d %H:%M:%S.%f"

[web_config]
host = "0.0.0.0"
port = 8080

[swagger_config]
url = "/swagger-ui/{_:.*}"
doc_url = "/api-docs/openapi.json"
